import { useState } from "react";
import Head from "next/head";
import TodoList from "../components/TodoList";
import styles from "../styles/Home.module.css";

const dummyList = [
  { id: 1, content: "Buy a new microphone" },
  { id: 2, content: "Clean the house" },
  { id: 3, content: "Practice some guitar" },
];

export default function Home() {
  const [sideBarOn, setSideBar] = useState(true);
  const toggleSidebar = () => {
    setSideBar(!sideBarOn);
  };

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Todo App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <nav className="bg-neutral-800 py-2 px-6 text-white flex justify-between">
          <div className="">
            <button
              type="button"
              className="hover:cursor-pointer"
              onClick={() => toggleSidebar()}
            >
              Show menu
            </button>
            <input
              type="text"
              placeholder="Search"
              className="text-black box-border px-2 ml-2"
            />
          </div>

          <span>
            <button
              type="button"
              className="hover:bg-neutral-700 text-lg px-3 hover:cursor-pointer"
            >
              +
            </button>
          </span>
        </nav>

        <div className={styles.content}>
          <aside
            className={`bg-neutral-50 text-zinc-500 w-64 pl-6 ${
              sideBarOn ? "" : "-ml-64"
            }`}
          >
            Sidebar
          </aside>
          <main className={styles.main}>
            <TodoList todos={dummyList} />
          </main>
        </div>
      </div>

      <footer className={styles.footer}>
        <p>Created by Hugo Perdomo</p>
      </footer>
    </>
  );
}
